language: python
python:
  - "3.5"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip install flake8
    - python setup.py install

# Os tests
os:
    - linux

# command to run tests
script:
    - pip install -r test-requirements.txt
    - flake8 kittypy